import { COLORS } from '../../config'
import { useCoreState } from '../../state'
export const useTheme = () => {
    const {theme}=useCoreState(state=> state.application);
    const isLight=theme==="light"
    const IsDark=theme==="dark"
    const FONT_COLOR = isLight? COLORS.FONT_COLOR_LIGHT:COLORS.FONT_COLOR_DARK
    const FONT_COLOR_RV = IsDark ? COLORS.FONT_COLOR_LIGHT:COLORS.FONT_COLOR_DARK
    const APP_BG_COLOR = isLight? COLORS.APP_BG_LIGTH:COLORS.APP_BG_DARK
    const APP_BG_COLOR_RV = IsDark? COLORS.APP_BG_LIGTH:COLORS.APP_BG_DARK
    const COMPONENT_BG_COLOR = isLight?COLORS.COMPONENT_BG_LIGHT:COLORS.COMPONENT_BG_DARK
    const COMPONENT_HIGHLIGHT_COLOR = isLight?COLORS.COMPONENT_HIGHLIGHT_COLOR_LIGHT:COLORS.COMPONENT_HIGHLIGHT_COLOR_DARK
    const COMPONENT_HIGHLIGHT_COLOR_Rv = IsDark? COLORS.COMPONENT_HIGHLIGHT_COLOR_LIGHT:COLORS.COMPONENT_HIGHLIGHT_COLOR_DARK
    const FONT_HIGHLIGHT_COLOR = isLight? COLORS.FONT_HIGHLIGHT_COLOR_LIGHT:COLORS.FONT_HIGHLIGHT_COLOR_DARK
    const FONT_HIGHLIGHT_COLOR_Rv = IsDark? COLORS.FONT_HIGHLIGHT_COLOR_LIGHT:COLORS.FONT_HIGHLIGHT_COLOR_DARK
   
    const COMPONENT_BG_COLOR_Rv = IsDark?COLORS.COMPONENT_BG_LIGHT:COLORS.COMPONENT_BG_DARK
    const APP_PRIMARY_COLOR =isLight? COLORS.PRIMARY_LIGHT: COLORS.APP_BG_DARK
    const APP_PRIMARY_COLOR_RV =IsDark? COLORS.PRIMARY_LIGHT: COLORS.APP_BG_DARK
  return (
    {
        FONT_COLOR,
        FONT_COLOR_RV, 
        APP_BG_COLOR,
        APP_BG_COLOR_RV, 
        APP_PRIMARY_COLOR,
        COMPONENT_BG_COLOR, 
        APP_PRIMARY_COLOR_RV,
        COMPONENT_BG_COLOR_Rv,
        FONT_HIGHLIGHT_COLOR_Rv,
        FONT_HIGHLIGHT_COLOR,
        COMPONENT_HIGHLIGHT_COLOR,
        COMPONENT_HIGHLIGHT_COLOR_Rv
    }
  )
}
