export enum COLORS {
    PRIMARY_LIGHT="#487A7B",
    PRIMARY_DARK="#000",
    APP_BG_LIGTH = "#F2F2F2",
    APP_BG_DARK = "#222",
    COMPONENT_BG_LIGHT = "#FFF",
    COMPONENT_BG_DARK = "#000",
    FONT_COLOR_LIGHT = "#333",
    FONT_COLOR_DARK = "#f2f2f2",
    COMPONENT_HIGHLIGHT_COLOR_LIGHT=  "#e6e6e6",
    COMPONENT_HIGHLIGHT_COLOR_DARK=  "#e6e6e6",
    FONT_HIGHLIGHT_COLOR_LIGHT= "#e6e6e6",
    FONT_HIGHLIGHT_COLOR_DARK=  "#e6e6e6" ,
  }
  